//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSpell
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int SpellId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Spell Spell { get; set; }
    }
}
